unit MathBase.SpecialFunctions;

{ Real Double special functions. The first 2.1 slice covers cylindrical
  Bessel J/Y of orders zero and one on a bounded, validated argument range.

  Formula sources:
    https://dlmf.nist.gov/10.2  (J series)
    https://dlmf.nist.gov/10.8  (Y series)
    https://dlmf.nist.gov/10.17 (large-argument expansion)
  The small-argument series loses accuracy through cancellation as X grows;
  the large-argument expansion becomes accurate only once X is sufficiently
  large. Middle-range Chebyshev coefficients bridge that gap and were generated
  from high-precision series by tools/generate_bessel_data.py. }

{$mode objfpc}{$H+}{$J-}

interface

{ J0 and J1 accept finite |X| <= 100. Outside this validated range they
  return NaN. J0(0)=1 and J1(0)=0; J0 is even and J1 is odd. }
function BesselJ0(const X: Double): Double;
function BesselJ1(const X: Double): Double;

{ Y0 and Y1 accept finite 0 < X <= 100. Both return -Infinity at zero; Y1
  also returns -Infinity when its pole exceeds Double range. Negative,
  nonfinite, or out-of-range arguments return NaN. }
function BesselY0(const X: Double): Double;
function BesselY1(const X: Double): Double;

implementation

uses
  Math;

{ BEGIN GENERATED BESSEL COEFFICIENTS }
{ Generated by tools/generate_bessel_data.py v1, Decimal precision 120. }
{ Chebyshev interpolation on [8, 16], 48 nodes, 40 coefficients. }
{ Formula source: https://dlmf.nist.gov/10.2 and https://dlmf.nist.gov/10.8. }
const
  J0Chebyshev: array[0..39] of Double = (
    -3.32757071513399108E-2,
    -2.72973786768856034E-2,
    -1.57547574209600824E-2,
    -1.97105061267964570E-1,
    3.88396594214053526E-2,
    5.68424062917470252E-2,
    -8.85904074702571111E-3,
    -6.04655909671513851E-3,
    8.29361866667398610E-4,
    3.43673179110411996E-4,
    -4.28910276251385126E-5,
    -1.23218453758903828E-5,
    1.42040890242856417E-6,
    3.06395666882318228E-7,
    -3.29068080930476561E-8,
    -5.61862016456436979E-9,
    5.65513025239583560E-10,
    7.93277603549392638E-11,
    -7.51587219232992200E-12,
    -8.90339593932641688E-13,
    7.96940119783780622E-14,
    8.14261483651086774E-15,
    -6.90703524584695219E-16,
    -6.18908327277302780E-17,
    4.98870721749267065E-18,
    3.97338806008743696E-19,
    -3.05074661704394298E-20,
    -2.18386171967241720E-21,
    1.60066991190402584E-22,
    1.03941009841955886E-23,
    -7.28716714305077179E-25,
    -4.32630739244591004E-26,
    2.90653883823670948E-27,
    1.58829092178254153E-28,
    -1.02424834432349241E-29,
    -5.18185680418853587E-31,
    3.21256461231234324E-32,
    1.51241218185090387E-33,
    -9.02722251696131202E-35,
    -3.97245544049885705E-36
  );
  J1Chebyshev: array[0..39] of Double = (
    1.86882513094999593E-1,
    -3.84587280723260655E-2,
    1.73233823756556791E-1,
    -5.42134854932861479E-2,
    -1.22423768145390063E-1,
    2.34658333495245574E-2,
    1.96822475839774996E-2,
    -3.11128889155257597E-3,
    -1.48070925452548524E-3,
    2.06158575117018475E-4,
    6.58200514713687463E-5,
    -8.29656300867408827E-6,
    -1.95009809602835894E-6,
    2.25890405897296761E-7,
    4.14737387067095398E-8,
    -4.45725075403683213E-9,
    -6.65912527523233630E-10,
    6.68534478798363459E-11,
    8.37343549375011243E-12,
    -7.89401851132952127E-13,
    -8.47906486099836051E-14,
    7.53826865082849405E-15,
    7.06807173380506213E-16,
    -5.94701196031533621E-17,
    -4.93740298839198325E-18,
    3.94367006758685783E-19,
    2.93320867173129515E-20,
    -2.23005345702680429E-21,
    -1.50046498264680808E-22,
    1.08844196388318867E-23,
    6.67966006155226631E-25,
    -4.63310757442709645E-26,
    -2.61163967388942535E-27,
    1.73545667516387154E-28,
    9.04034705176817874E-30,
    -5.76551018606555500E-31,
    -2.79023555617590325E-32,
    1.71061160966628412E-33,
    7.72698024826891389E-35,
    -4.56066855636516391E-36
  );
  Y0Chebyshev: array[0..39] of Double = (
    1.87644242402624852E-1,
    -3.71589118317390903E-2,
    1.72026720050605922E-1,
    -4.53264276025220173E-2,
    -1.25066336101071474E-1,
    2.13946409536613331E-2,
    2.03565636051884068E-2,
    -2.95745213330277308E-3,
    -1.53929399678976296E-3,
    2.00882916572971138E-4,
    6.84512997383048775E-5,
    -8.19919749168724856E-6,
    -2.02511515982470492E-6,
    2.25139725549853246E-7,
    4.29700838860601874E-8,
    -4.46472895888127956E-9,
    -6.88315157150652544E-10,
    6.71848429907763621E-11,
    8.63312767074907685E-12,
    -7.94622689982501646E-13,
    -8.72628678823227373E-14,
    7.60311604309732353E-15,
    7.24987900154830262E-16,
    -5.98682296626861837E-17,
    -5.08034030226358219E-18,
    4.01308507406739519E-19,
    2.94572472473407211E-20,
    -2.15855508303162524E-21,
    -1.68658188575764795E-22,
    1.35446098637761640E-23,
    2.55185694145745240E-25,
    2.43414393533746038E-26,
    -1.45279659152391041E-26,
    2.15676123454664144E-27,
    -3.21914773337179426E-28,
    5.47790598815838128E-29,
    -9.28965381846884574E-30,
    1.55189134760701413E-30,
    -2.59528098549073973E-31,
    4.34940469725697590E-32
  );
  Y1Chebyshev: array[0..39] of Double = (
    4.25732693773345723E-2,
    2.28630361544989012E-2,
    2.39938134614650272E-2,
    1.94889756205104824E-1,
    -4.39958279423179987E-2,
    -5.52429159970381245E-2,
    9.49077444183533399E-3,
    5.82677481852709584E-3,
    -8.60308024724371779E-4,
    -3.30401168631956015E-4,
    4.36650998539983426E-5,
    1.18553300595683721E-5,
    -1.43048635028152449E-6,
    -2.95360899379857415E-7,
    3.29218657925216073E-8,
    5.42968782256389722E-9,
    -5.63601399087989373E-10,
    -7.68334346413231295E-11,
    7.46976633360970496E-12,
    8.64714395418562135E-13,
    -7.91492212240606794E-14,
    -7.91428340466523837E-15,
    6.83497228461217683E-16,
    6.05834970378945064E-17,
    -4.98741265967342965E-18,
    -3.80586589268479974E-19,
    2.89436829108143321E-20,
    2.35762494694939991E-21,
    -1.96810710112608699E-22,
    -3.58969311130721905E-24,
    -4.13867087854321410E-25,
    2.38092300878959554E-25,
    -3.65747778770150511E-26,
    5.64484623513388914E-27,
    -9.88217506995467316E-28,
    1.72295088401838898E-28,
    -2.95839590677505914E-29,
    5.08131966939967476E-30,
    -8.73969137020829406E-31,
    1.50285796967265180E-31
  );
{ END GENERATED BESSEL COEFFICIENTS }

const
  EulerGamma = 0.57721566490153286061;
  TwoOverPi = 0.63661977236758134308;
  MaxBesselArgument = 100.0;

function ChebyshevValue(const X: Double; const Coefficients: array of Double): Double;
var
  I: Integer;
  T, B0, B1, B2: Double;
begin
  T := (X - 12.0) * 0.25;
  B1 := 0.0;
  B2 := 0.0;
  for I := High(Coefficients) downto 1 do
  begin
    B0 := 2.0 * T * B1 - B2 + Coefficients[I];
    B2 := B1;
    B1 := B0;
  end;
  Result := T * B1 - B2 + 0.5 * Coefficients[0];
end;

function JSeries(const X: Double; const Order: Integer): Double;
var
  K: Integer;
  Q, Term: Double;
begin
  Q := Sqr(0.5 * X);
  if Order = 0 then
    Term := 1.0
  else
    Term := 0.5 * X;
  Result := Term;
  for K := 1 to 80 do
  begin
    Term := -Term * Q / (K * (K + Order));
    Result := Result + Term;
    if Abs(Term) < 1E-17 then
      Break;
  end;
end;

function Y0Series(const X: Double): Double;
var
  K: Integer;
  Q, Term, Harmonic, SeriesSum: Double;
begin
  Q := Sqr(0.5 * X);
  Term := 1.0;
  Harmonic := 0.0;
  SeriesSum := 0.0;
  for K := 1 to 80 do
  begin
    Harmonic := Harmonic + 1.0 / Double(K);
    Term := -Term * Q / (K * K);
    SeriesSum := SeriesSum - Harmonic * Term;
    if Abs(Term) < 1E-17 then
      Break;
  end;
  Result := TwoOverPi * ((Ln(X) - Ln(2.0) + EulerGamma) *
    JSeries(X, 0) + SeriesSum);
end;

function Y1Series(const X: Double): Double;
var
  K: Integer;
  Q, Term, Harmonic, SeriesSum: Double;
begin
  Q := Sqr(0.5 * X);
  Term := 0.5 * X;
  Harmonic := 0.0;
  SeriesSum := Term;
  for K := 1 to 80 do
  begin
    Harmonic := Harmonic + 1.0 / Double(K);
    Term := -Term * Q / (K * (K + 1));
    SeriesSum := SeriesSum + (2.0 * Harmonic + 1.0 / Double(K + 1)) * Term;
    if Abs(Term) < 1E-17 then
      Break;
  end;
  Result := -TwoOverPi / X + TwoOverPi * (Ln(X) - Ln(2.0) +
    EulerGamma) * JSeries(X, 1) - SeriesSum / Pi;
end;

procedure AsymptoticJY(const X: Double; const Order: Integer;
  out JValue, YValue: Double);
var
  K: Integer;
  Term, NextTerm, P, Q, Phase, Amplitude: Double;
begin
  P := 1.0;
  Q := 0.0;
  Term := 1.0;
  for K := 1 to 96 do
  begin
    NextTerm := Term * (4.0 * Order * Order - Sqr(2 * K - 1)) /
      (8.0 * K * X);
    if Abs(NextTerm) > Abs(Term) then
      Break;
    Term := NextTerm;
    if Odd(K) then
    begin
      if Odd((K - 1) div 2) then
        Q := Q - Term
      else
        Q := Q + Term;
    end
    else if Odd(K div 2) then
      P := P - Term
    else
      P := P + Term;
    if Abs(Term) < 1E-18 then
      Break;
  end;
  Phase := X - (Order * 0.5 + 0.25) * Pi;
  Amplitude := Sqrt(2.0 / (Pi * X));
  JValue := Amplitude * (P * Cos(Phase) - Q * Sin(Phase));
  YValue := Amplitude * (P * Sin(Phase) + Q * Cos(Phase));
end;

function BesselJ0(const X: Double): Double;
var
  AX, UnusedY: Double;
begin
  if IsNan(X) or IsInfinite(X) or (Abs(X) > MaxBesselArgument) then
    Exit(NaN);
  AX := Abs(X);
  if AX <= 8.0 then
    Result := JSeries(AX, 0)
  else if AX < 16.0 then
    Result := ChebyshevValue(AX, J0Chebyshev)
  else
    AsymptoticJY(AX, 0, Result, UnusedY);
end;

function BesselJ1(const X: Double): Double;
var
  AX, UnusedY: Double;
begin
  if IsNan(X) or IsInfinite(X) or (Abs(X) > MaxBesselArgument) then
    Exit(NaN);
  AX := Abs(X);
  if AX <= 8.0 then
    Result := JSeries(AX, 1)
  else if AX < 16.0 then
    Result := ChebyshevValue(AX, J1Chebyshev)
  else
    AsymptoticJY(AX, 1, Result, UnusedY);
  if X < 0.0 then
    Result := -Result;
end;

function BesselY0(const X: Double): Double;
var
  UnusedJ: Double;
begin
  if IsNan(X) or IsInfinite(X) or (X < 0.0) or
    (X > MaxBesselArgument) then
    Exit(NaN);
  if X = 0.0 then
    Exit(-Infinity);
  if X <= 8.0 then
    Result := Y0Series(X)
  else if X < 16.0 then
    Result := ChebyshevValue(X, Y0Chebyshev)
  else
    AsymptoticJY(X, 0, UnusedJ, Result);
end;

function BesselY1(const X: Double): Double;
var
  UnusedJ: Double;
begin
  if IsNan(X) or IsInfinite(X) or (X < 0.0) or
    (X > MaxBesselArgument) then
    Exit(NaN);
  if X = 0.0 then
    Exit(-Infinity);
  { Guard the leading 2/(Pi*X) pole before division: FPC raises EOverflow
    for a finite quotient outside Double instead of returning infinity. }
  if (X < 1.0) and (X * MaxDouble < TwoOverPi) then
    Exit(-Infinity);
  if X <= 8.0 then
    Result := Y1Series(X)
  else if X < 16.0 then
    Result := ChebyshevValue(X, Y1Chebyshev)
  else
    AsymptoticJY(X, 1, UnusedJ, Result);
end;

end.
